# -*- coding: utf-8 -*-
"""Thesis_Machine_Learning_Finalized (13).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRfa1t_SDPEQImN6TK65b2h6EBsqn9lK

# Thesis Machine Learning Models



Here the Machine Learning models will be implemented. The models consists of:
  - Naive Bayes
  - Support Machine Vector
  - Logistic Regression



Order of progress:

  - Import Packages
  - Uploading Dataset
  - Checking Dataset
  - Splitting data into Training/Validation/Testing (70/15/15)
  - Label Encoding for Sentiments
  - TF-IDF vectorizing
  - Implementing the models
  - Transform val/test using trained TF-IDF
  - Train ML models
"""

!pip install lime

from google.colab import drive
drive.mount('/content/drive')

# @title Import Packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import os
import re


from sklearn.utils.class_weight import compute_class_weight

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import ComplementNB
from sklearn.svm import SVC, LinearSVC

from sklearn.metrics import accuracy_score, f1_score, classification_report


import shap
import lime
import lime.lime_text
from collections import defaultdict

# @title Import Dataset
df = pd.read_csv('/content/drive/MyDrive/Thesis Codes/Data/Data after preprocessing/Data_Thesis_after_pre.csv')
pd.set_option('display.max_colwidth', None)

# @title Seeds
SEEDS = [42, 7, 123, 999, 2024, 13, 77, 31, 55, 256]

# the text and aspect are combined
# aspect is first being lowercased
df['entity'] = df['entity'].replace({
    'Hamas'   : 'hamas',
    'Israel'  : 'israel'
})

df['Pipeline_text'] = df['entity'] + " [SEP] " + df ['New_text']

# @title Label Encoding

classes_ordered = ['very negative', 'mildly negative', 'neutral', 'mildly positive', 'very positive']

# Create encoder and manually set classes
le = LabelEncoder()
le.classes_ = np.array(classes_ordered)

df['sentiment_label'] = np.array([list(le.classes_).index(label) for label in df['sentiment']])

'''
0 = very negative
1 = mildly negative
2 = neutral
3 = mildly positive
4 = very positive
'''

df[[ 'sentiment','sentiment_label']]

results = []
for seed in SEEDS:
    print(f"\n===== Seed {seed} =====")

    # reproducibility
    np.random.seed(seed)
    random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)




    # Splitting
    X_train, X_temp, y_train, y_temp = train_test_split(
        df['Pipeline_text'],
        df['sentiment_label'],
        test_size=0.3,
        stratify=df['sentiment_label'],
        random_state=seed
    )

    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=0.5,
        stratify=y_temp,
        random_state=seed
    )



    vectorizer = TfidfVectorizer(
        ngram_range=(1,2),   # unigrams + bigrams
        max_features=50000,  # limit vocabulary size
        min_df = 5,            # Loses the unimportant words
        stop_words=None
        )


    # Fit on training set
    X_train_tfidf = vectorizer.fit_transform(X_train)

    # Transform val/test
    X_val_tfidf = vectorizer.transform(X_val)
    X_test_tfidf = vectorizer.transform(X_test)

    print("Number of features:", len(vectorizer.get_feature_names_out()))


    models = {

    'ComplementNB': ComplementNB(alpha=1),

    'LogisticRegression': LogisticRegression(max_iter=1000,
                                             solver='saga',
                                             n_jobs=-1,
                                             class_weight='balanced',
                                             random_state=seed),

    'Linear Support Vector Machine': LinearSVC(class_weight='balanced',
                                               random_state=seed)
    }


    for name, model in models.items():
        model.fit(X_train_tfidf, y_train)

        # Validation (optional reporting)
        y_val_pred = model.predict(X_val_tfidf)

        val_acc = accuracy_score(y_val, y_val_pred)
        val_f1_macro = f1_score(y_val, y_val_pred, average='macro')
        val_f1_weighted = f1_score(y_val, y_val_pred, average='weighted')


        y_test_pred = model.predict(X_test_tfidf)

        test_acc = accuracy_score(y_test, y_test_pred)
        test_f1_macro = f1_score(y_test, y_test_pred, average='macro')
        test_f1_weighted = f1_score(y_test, y_test_pred, average='weighted')

        print(f"\n{name} (seed={seed})")
        print(f"Validation F1 (macro): {val_f1_macro:.4f}")
        print(f"Test Accuracy: {test_acc:.4f}")
        print(f"Test F1 (macro): {test_f1_macro:.4f}")
        print(f"Test F1 (weighted): {test_f1_weighted:.4f}")

        results.append({
            "seed": seed,
            "model": name,
            "val_f1_macro": val_f1_macro,
            "test_accuracy": test_acc,
            "test_f1_macro": test_f1_macro,
            "test_f1_weighted": test_f1_weighted
        })

df_results = pd.DataFrame(results)

mean_results = df_results.groupby("model")[[
    "test_accuracy",
    "test_f1_macro",
    "test_f1_weighted"
]].mean()

std_results = df_results.groupby("model")[[
    "test_accuracy",
    "test_f1_macro",
    "test_f1_weighted"
]].std()

summary = mean_results.round(4).astype(str) + " ± " + std_results.round(4).astype(str)
print("\n===== ML Model Results Across Seeds =====")
print(summary.to_string())

# @title Getting the model


best_seed = 42
best_model_name = "LogisticRegression"

best_row = df_results[
    (df_results["seed"] == best_seed) &
    (df_results["model"] == best_model_name)
].iloc[0]

print(best_row)

# @title Results per Entity

print(f"\nApplying results for: {best_model_name} (seed={best_seed})")

# Ensure predictions are made for the entire X_test_tfidf
y_test_pred_best_model = model.predict(X_test_tfidf)

df_test     = df.loc[X_test.index].reset_index(drop=True)
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

hamas_preds  = y_test_pred_best_model[hamas_mask.values]
israel_preds = y_test_pred_best_model[israel_mask.values]
hamas_true   = np.array(y_test)[hamas_mask.values]
israel_true  = np.array(y_test)[israel_mask.values]

print("\n===== Best Model - Hamas Entity =====")
print(classification_report(hamas_true, hamas_preds, target_names=le.classes_, zero_division=0))

print("\n===== Best Model - Israel Entity =====")
print(classification_report(israel_true, israel_preds, target_names=le.classes_, zero_division=0))

"""# XAI Setup

Getting the best model with the best seed
    - Lime
    - Common words


"""

# @title Split again (same as before)
# Re-split using best seed and model , adjust this accordingly
np.random.seed(42)

X_train, X_temp, y_train, y_temp = train_test_split(
    df['Pipeline_text'],
    df['sentiment_label'],
    test_size=0.3,
    stratify=df['sentiment_label'],
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    stratify=y_temp,
    random_state=42
)

# @title Vectorize with custom stop words to remove noise
custom_stop_words = [
    'israel sep', 'israel', 'hamas',
    'and', 'will', 'for', 'you', 'are', 'with', 'our', 'this', 'hamas [SEP]', 'israel [SEP]'
]

vectorizer = TfidfVectorizer(
    ngram_range=(1,2),
    max_features=50000,
    min_df=5,
    stop_words=custom_stop_words,
    token_pattern=r'(?u)\b[a-z]{3,}\b' # Matches words with 3 or more characters
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf  = vectorizer.transform(X_test)
feature_names = vectorizer.get_feature_names_out()

model = LogisticRegression(
    max_iter=1000,
    solver='saga',
    n_jobs=-1,
    class_weight='balanced',
    random_state=42
)
model.fit(X_train_tfidf, y_train)

np.random.seed(42)
sample_size  = min(1000, X_test_tfidf.shape[0])
idx          = np.random.choice(X_test_tfidf.shape[0], sample_size, replace=False)
X_sample     = X_test_tfidf[idx]
df_sample    = df.iloc[X_test.index].iloc[idx].reset_index(drop=True)
pred_classes = model.predict(X_sample)

hamas_mask = df_sample["entity"] == "hamas"
israel_mask = df_sample["entity"] == "israel"

print(f"Hamas samples:  {hamas_mask.sum()}")
print(f"Israel samples: {israel_mask.sum()}")

"""## LIME

  - 3 examples of per entity and sentiments
  - Top contributing words SNS plot
"""

def predict_proba_for_lime(texts):
    vectors = vectorizer.transform(texts)
    return model.predict_proba(vectors)

explainer_lime = lime.lime_text.LimeTextExplainer(class_names=classes_ordered)

# @title Setup df_test for LIME
df_test = df.loc[X_test.index].reset_index(drop=True)
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

# Words to exclude from LIME analysis
noise_words = {
    'israel', 'hamas', 'sep', 'user', 'the', 'a', 'an', 'and',
    'or', 'of', 'in', 'to', 'for', 'is', 'are', 'was', 'were',
    'we', 'you', 'it', 'its', 'with', 'has', 'have', 'that',
    'this', 'be', 'been', 'by', 'at', 'from', 'on', 'as', 'via',
    'see', 'did','SEP', '873', 'our', 'but', 'not', 'amp', 'amid'
}

# @title LIME - Individual Examples (LR) -  iloc0

selected_texts = {
    ('hamas', 'very negative'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[0]['Pipeline_text'],
    ('hamas', 'mildly negative'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[0]['Pipeline_text'],
    ('hamas', 'neutral'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[0]['Pipeline_text'],
    ('hamas', 'mildly positive'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[0]['Pipeline_text'],
    ('hamas', 'very positive'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[0]['Pipeline_text'],

    ('israel', 'very negative'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==0)].iloc[0]['Pipeline_text'],
    ('israel', 'mildly negative'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==1)].iloc[0]['Pipeline_text'],
    ('israel', 'neutral'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==2)].iloc[0]['Pipeline_text'],
    ('israel', 'mildly positive'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==3)].iloc[0]['Pipeline_text'],
    ('israel', 'very positive'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==4)].iloc[0]['Pipeline_text'],


}

for (entity, sentiment), text in selected_texts.items():
    text = text.replace("hamas [SEP] ", "").replace("israel [SEP] ", "")
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=1000,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"{entity.upper()} - {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME_LR__iloc0{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Individual Examples (LR) -  iloc1

selected_texts = {
    ('hamas', 'very negative'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[1]['Pipeline_text'],
    ('hamas', 'mildly negative'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[1]['Pipeline_text'],
    ('hamas', 'neutral'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[1]['Pipeline_text'],
    ('hamas', 'mildly positive'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[1]['Pipeline_text'],
    ('hamas', 'very positive'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[1]['Pipeline_text'],

    ('israel', 'very negative'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==0)].iloc[1]['Pipeline_text'],
    ('israel', 'mildly negative'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==1)].iloc[1]['Pipeline_text'],
    ('israel', 'neutral'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==2)].iloc[1]['Pipeline_text'],
    ('israel', 'mildly positive'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==3)].iloc[1]['Pipeline_text'],
    ('israel', 'very positive'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==4)].iloc[1]['Pipeline_text'],


}

for (entity, sentiment), text in selected_texts.items():
    text = text.replace("hamas [SEP] ", "").replace("israel [SEP] ", "")
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=1000,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"{entity.upper()} - {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME_LR_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Individual Examples (LR) -  iloc2

selected_texts = {
    ('hamas', 'very negative'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[2]['Pipeline_text'],
    ('hamas', 'mildly negative'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[2]['Pipeline_text'],
    ('hamas', 'neutral'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[2]['Pipeline_text'],
    ('hamas', 'mildly positive'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[2]['Pipeline_text'],
    ('hamas', 'very positive'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[2]['Pipeline_text'],

    ('israel', 'very negative'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==0)].iloc[2]['Pipeline_text'],
    ('israel', 'mildly negative'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==1)].iloc[2]['Pipeline_text'],
    ('israel', 'neutral'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==2)].iloc[2]['Pipeline_text'],
    ('israel', 'mildly positive'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==3)].iloc[2]['Pipeline_text'],
    ('israel', 'very positive'):  df_test[(df_test['entity']=='israel')  & (df_test['sentiment_label']==4)].iloc[2]['Pipeline_text'],


}

for (entity, sentiment), text in selected_texts.items():
    text = text.replace("hamas [SEP] ", "").replace("israel [SEP] ", "")
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=1000,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"{entity.upper()} - {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME_LR_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Individual Examples (LR)

selected_texts = {
    ('hamas', 'very negative'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[1]['Pipeline_text'],
    ('hamas', 'very positive'):  df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[0]['Pipeline_text'],

    ('israel', 'very negative'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[0]['Pipeline_text'],
    ('israel', 'very positive'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[0]['Pipeline_text'],

    ('israel', 'neutral'):       df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[0]['Pipeline_text'],
    ('hamas', 'neutral'):       df_test[(df_test['entity']=='hamas') & (df_test['sentiment_label']==2)].iloc[0]['Pipeline_text'],
}

for (entity, sentiment), text in selected_texts.items():
    text = text.replace("hamas [SEP] ", "").replace("israel [SEP] ", "")
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=1000,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"{entity.upper()} - {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME_LR_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title Heatmap top 10 words per entity and sentiment.

word_contributions = defaultdict(list)

for entity in ['hamas', 'israel']:
    for sentiment_idx, sentiment in enumerate(le.classes_):
        subset = df_test[
            (df_test['entity'] == entity) &
            (df_test['sentiment_label'] == sentiment_idx)
        ]['Pipeline_text'].head(20)

        for text in subset:
            text = text.replace("hamas [SEP] ", "").replace("israel [SEP] ", "")
            try:
                exp = explainer_lime.explain_instance(
                    text,
                    predict_proba_for_lime,
                    num_features=10,
                    num_samples=500,
                    top_labels=len(le.classes_)
                )
                word_contributions[(entity, sentiment)].extend(
                    [(word, weight)
                     for word, weight in exp.as_list(label=sentiment_idx)
                     if word.lower() not in noise_words]
                )
            except Exception as e:
                print(f"Skipped ({entity}, {sentiment}): {e}")

#  Heatmap plot
for entity in ['hamas', 'israel']:
    top_words_per_sentiment = {}
    top_scores_per_sentiment = {}

    for sentiment in le.classes_:
        contributions = word_contributions.get((entity, sentiment), [])
        word_totals = defaultdict(float)
        for word, weight in contributions:
            word_totals[word] += weight

        top_words = sorted(word_totals.items(), key=lambda x: abs(x[1]), reverse=True)[:10]

        if len(top_words) < 10:
            top_words += [('', 0.0)] * (10 - len(top_words))

        top_words_per_sentiment[sentiment]  = [w for w, _ in top_words]
        top_scores_per_sentiment[sentiment] = [s for _, s in top_words]

    score_data = pd.DataFrame(top_scores_per_sentiment,
                               index=[f"#{i+1}" for i in range(10)])
    word_data  = pd.DataFrame(top_words_per_sentiment,
                               index=[f"#{i+1}" for i in range(10)])

    fig, ax = plt.subplots(figsize=(12, 4))
    sns.heatmap(
        score_data, ax=ax, cmap='RdYlGn', center=0,
        cbar_kws={'label': 'Contribution Score'},
        linewidths=1, linecolor='white', annot=False
    )

    for i in range(10):
        for j, sentiment in enumerate(le.classes_):
            word = word_data.iloc[i, j] if j < word_data.shape[1] else ''
            ax.text(j + 0.5, i + 0.5, word, ha='center', va='center',
                    fontsize=11, fontweight='bold', color='black')

    ax.set_title(f"Top 10 Words per Sentiment — Logistic Regression — {entity.upper()}", fontsize=13)
    ax.set_xticklabels(le.classes_, rotation=15)
    ax.set_yticklabels([f"#{i+1}" for i in range(10)], rotation=0)
    plt.tight_layout()
    plt.savefig(f"LIME_heatmap_LR_{entity}.png", dpi=300, bbox_inches='tight')
    plt.show()