# -*- coding: utf-8 -*-
"""DeBERTa_V3_base_2_April_2026 (7).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vPaTrExlKJiqNzKdo-QumB0d9sXQJE-

DeBERTa-V3 base
"""

!pip install sentencepiece
!pip install --upgrade transformers accelerate
!pip install lime

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader
from sklearn.utils.class_weight import compute_class_weight

from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_scheduler
from sklearn.preprocessing import LabelEncoder
import torch.nn.functional as F

from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm

from sklearn.metrics import classification_report, f1_score, accuracy_score

import torch

import random

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import lime
import lime.lime_text
from collections import defaultdict

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Thesis Codes/Data/Data after preprocessing/Data_Thesis_after_pre.csv')
pd.set_option('display.max_colwidth', None)
df

# @title Config
class Config:
    checkpoint = "microsoft/deberta-v3-base"
    max_length = 128
    batch_size = 16
    lr = 2e-5
    epochs = 3

# @title Setting up Seeds **adjust this per run**
SEEDS = [42]
# SEEDS = [7]
# SEEDS = [123]

# @title Setting up device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

# @title setting entity lowercase
df['entity'] = df['entity'].replace({
    'Hamas':'hamas',
    'Israel':'israel'
    }
)

# @title Labelencoding

classes_ordered = ['very negative', 'mildly negative', 'neutral', 'mildly positive', 'very positive']

# Create encoder and manually set classes
le = LabelEncoder()
le.classes_ = np.array(classes_ordered)

df['sentiment_label'] = np.array([list(le.classes_).index(label) for label in df['sentiment']])

'''
0 = very negative
1 = mildly negative
2 = neutral
3 = mildly positive
4 = very positive
'''

df[["New_text", 'sentiment','sentiment_label']]

# @title Setting up Tokenizing and model

tokenizer = AutoTokenizer.from_pretrained(Config.checkpoint)

def prepare_data(df, seed):
    X_train, X_temp, y_train, y_temp = train_test_split(
        df['New_text'],
        df['sentiment_label'],
        test_size=0.3,
        stratify=df['sentiment_label'],
        random_state=seed
    )


    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=0.5,
        stratify=y_temp,
        random_state=seed
    )

    X_train_entity = df.loc[X_train.index, 'entity']
    X_val_entity   = df.loc[X_val.index, 'entity']
    X_test_entity  = df.loc[X_test.index, 'entity']



    return X_train, X_train_entity, y_train, \
           X_val, X_val_entity, y_val, \
           X_test, X_test_entity, y_test

def tokenize(texts, entities, tokenizer):
    combined = texts + " [SEP] " + entities

    return tokenizer(
        combined.tolist(),
        padding=True,
        truncation=True,
        max_length=Config.max_length,
        return_tensors="pt"
    )

def create_datasets(train_enc, val_enc, test_enc, y_train, y_val, y_test):
    train_dataset = TensorDataset(
        train_enc["input_ids"],
        train_enc["attention_mask"],
        torch.tensor(y_train.values)
    )

    val_dataset = TensorDataset(
        val_enc["input_ids"],
        val_enc["attention_mask"],
        torch.tensor(y_val.values)
    )

    test_dataset = TensorDataset(
        test_enc["input_ids"],
        test_enc["attention_mask"],
        torch.tensor(y_test.values)
    )

    return train_dataset, val_dataset, test_dataset

def train_model(model, train_loader, optimizer, scheduler, loss_fn, device):
    model.train()
    total_loss = 0

    for input_ids, attention_mask, labels in train_loader:
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        labels = labels.to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = loss_fn(outputs.logits, labels)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        scheduler.step()
        optimizer.zero_grad()

        total_loss += loss.item()

    return total_loss / len(train_loader)

def evaluate(model, loader, device):
    model.eval()
    preds = []
    true = []

    with torch.no_grad():
        for input_ids, attention_mask, labels in loader:
            input_ids = input_ids.to(device)
            attention_mask = attention_mask.to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            batch_preds = torch.argmax(outputs.logits, dim=-1)

            preds.extend(batch_preds.cpu().numpy())
            true.extend(labels.numpy())

    return true, preds

def run_experiment(df, seed, tokenizer, device, le):


    # Setting seeds
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


    # Data
    X_train, X_train_entity, y_train, \
    X_val, X_val_entity, y_val, \
    X_test, X_test_entity, y_test = prepare_data(df, seed)

    # Tokenization
    train_enc = tokenize(X_train, X_train_entity, tokenizer)
    val_enc   = tokenize(X_val, X_val_entity, tokenizer)
    test_enc  = tokenize(X_test, X_test_entity, tokenizer)

    # Dataset
    train_dataset, val_dataset, test_dataset = create_datasets(
        train_enc, val_enc, test_enc, y_train, y_val, y_test
    )

    g = torch.Generator()
    g.manual_seed(seed)
    train_loader = DataLoader(train_dataset, batch_size=Config.batch_size, shuffle=True, generator=g)
    val_loader   = DataLoader(val_dataset, batch_size=Config.batch_size)
    test_loader  = DataLoader(test_dataset, batch_size=Config.batch_size)


    model = AutoModelForSequenceClassification.from_pretrained(
    Config.checkpoint,
    num_labels=5
    ).to(device)
    model = model.float()


    optimizer = torch.optim.AdamW(model.parameters(), lr=Config.lr)

    loss_fn = torch.nn.CrossEntropyLoss()


    num_epochs = Config.epochs
    num_training_steps = num_epochs * len(train_loader)

    scheduler = get_scheduler(
        "linear",
        optimizer=optimizer,
        num_warmup_steps=0,
        num_training_steps=num_training_steps
    )

    # Train
    for epoch in range(num_epochs):
        loss = train_model(model, train_loader, optimizer, scheduler, loss_fn, device)
        print(f"Epoch {epoch+1} Loss: {loss:.4f}")

    # Evaluate
    y_true, y_pred = evaluate(model, test_loader, device)


    print("\n===== Classification Report =====")
    print(classification_report(y_true, y_pred, target_names=le.classes_, zero_division=0))


    macro = f1_score(y_true, y_pred, average='macro')
    weighted = f1_score(y_true, y_pred, average='weighted')
    acc = accuracy_score(y_true, y_pred)

    return macro, weighted, acc, model

# @title 42 Seed
results = []

for seed in SEEDS:
    print(f"\n===== Seed {seed} =====")
    macro, weighted, acc, model = run_experiment(df, seed, tokenizer, device, le)
    results.append((macro, weighted, acc))

results = np.array(results)

print("\n===== FINAL RESULTS =====")
print(f"Macro F1: {results[:,0].mean():.4f} ± {results[:,0].std():.4f}")
print(f"Weighted F1: {results[:,1].mean():.4f} ± {results[:,1].std():.4f}")
print(f"Accuracy: {results[:,2].mean():.4f} ± {results[:,2].std():.4f}")

# @title 7 Seed
results = []

for seed in SEEDS:
    print(f"\n===== Seed {seed} =====")
    macro, weighted, acc, model = run_experiment(df, seed, tokenizer, device, le)
    results.append((macro, weighted, acc))

results = np.array(results)

print("\n===== FINAL RESULTS =====")
print(f"Macro F1: {results[:,0].mean():.4f} ± {results[:,0].std():.4f}")
print(f"Weighted F1: {results[:,1].mean():.4f} ± {results[:,1].std():.4f}")
print(f"Accuracy: {results[:,2].mean():.4f} ± {results[:,2].std():.4f}")

# @title 123 Seed
results = []

for seed in SEEDS:
    print(f"\n===== Seed {seed} =====")
    macro, weighted, acc, model = run_experiment(df, seed, tokenizer, device, le)
    results.append((macro, weighted, acc))

results = np.array(results)

print("\n===== FINAL RESULTS =====")
print(f"Macro F1: {results[:,0].mean():.4f} ± {results[:,0].std():.4f}")
print(f"Weighted F1: {results[:,1].mean():.4f} ± {results[:,1].std():.4f}")
print(f"Accuracy: {results[:,2].mean():.4f} ± {results[:,2].std():.4f}")

# Averages
print("\n===== Averages =====")
import numpy as np

macro_f1_mean = np.mean([0.6845 ,0.6871, 0.6843])
macro_f1_std = np.std([0.6845 ,0.6871, 0.6843])
print(f'Macro F1:     {macro_f1_mean:.4f} ±  {macro_f1_std:.3f}')


weighted_f1_mean = np.mean([0.7207 ,0.7217, 0.7200])
weighted_f1_std = np.std([0.7207 ,0.7217, 0.7200])
print(f'Weighted F1:  {weighted_f1_mean:.4f} ±  {weighted_f1_std:.3f}')


accuracy_mean = np.mean([0.7213 ,0.7219, 0.7207])
accuracy_std = np.std([0.7213 ,0.7219, 0.7207])
print(f'Accuracy:     {accuracy_mean:.4f} ±  {accuracy_std:.3f}')

# @title Entity-Level Evaluation (Seed 42)

X_train_e, X_temp_e, y_train_e, y_temp_e = train_test_split(
    df['New_text'], df['sentiment_label'],
    test_size=0.3, stratify=df['sentiment_label'], random_state=42
)
X_val_e, X_test_e, y_val_e, y_test_e = train_test_split(
    X_temp_e, y_temp_e,
    test_size=0.5, stratify=y_temp_e, random_state=42
)

df_test     = df.loc[X_test_e.index].reset_index(drop=True)
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

X_test_entity = df.loc[X_test_e.index, 'entity']
test_enc = tokenize(X_test_e, X_test_entity, tokenizer)
test_dataset = TensorDataset(
    test_enc["input_ids"],
    test_enc["attention_mask"],
    torch.tensor(y_test_e.values)
)
test_loader = DataLoader(test_dataset, batch_size=Config.batch_size)

y_true, y_pred = evaluate(model, test_loader, device)
y_pred_arr = np.array(y_pred)
y_true_arr = np.array(y_true)

hamas_preds  = y_pred_arr[hamas_mask.values]
israel_preds = y_pred_arr[israel_mask.values]
hamas_true   = y_true_arr[hamas_mask.values]
israel_true  = y_true_arr[israel_mask.values]

print("\n===== DeBERTa-v3 - Israel Entity =====")
print(classification_report(israel_true, israel_preds, target_names=le.classes_, zero_division=0))

print("\n===== DeBERTa-v3 - Hamas Entity =====")
print(classification_report(hamas_true, hamas_preds, target_names=le.classes_, zero_division=0))

# @title Confusion Matrix (Seed 42)

y_true_arr = np.array(y_true)
y_pred_arr = np.array(y_pred)
cm = confusion_matrix(y_true_arr, y_pred_arr)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=le.classes_)

fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(ax=ax, cmap='Blues', colorbar=False)
plt.xticks(rotation=45, ha='right')
plt.title('Confusion Matrix - DeBERTa-v3 (Seed 42)')
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Israel
cm_israel = confusion_matrix(israel_true, israel_preds)
ConfusionMatrixDisplay(confusion_matrix=cm_israel, display_labels=le.classes_).plot(ax=axes[0], cmap='Blues', colorbar=False)
axes[0].set_title('Confusion Matrix DeBERTa V3 - Israel')
axes[0].tick_params(axis='x', rotation=45)

# Hamas
cm_hamas = confusion_matrix(hamas_true, hamas_preds)
ConfusionMatrixDisplay(confusion_matrix=cm_hamas, display_labels=le.classes_).plot(ax=axes[1], cmap='Blues', colorbar=False)
axes[1].set_title('Confusion Matrix DeBERTa V3 - Hamas')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

# @title QUALITATIVE ANALYSIS
def predict(input_text, model, tokenizer):
    model.eval()

    inputs = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=Config.max_length
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = F.softmax(outputs.logits, dim=-1)

    probs = probs.cpu().numpy()[0]
    pred_idx = probs.argmax()

    label = le.classes_[pred_idx]
    score = probs[pred_idx]

    return label, score

print("\n===== QUALITATIVE ANALYSIS =====\n")

examples = list(df[['sentiment','entity', 'New_text']].sample(20, random_state=42).itertuples(index=False, name=None))

for sentiment, entity, text in examples:
    input_text = entity + " [SEP] " + text
    label, score = predict(input_text, model, tokenizer)

    print(f"Entity: {entity}")
    print(f"Annotated Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Prediction: {label} ({score:.3f})\n")

# @title LIME Setup

def predict_proba_for_lime(texts):
    model.eval()
    inputs = tokenizer(
        texts,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=Config.max_length
    ).to(device)
    with torch.no_grad():
        outputs = model(**inputs)
        probs = F.softmax(outputs.logits, dim=-1)
    return probs.cpu().numpy()

explainer_lime = lime.lime_text.LimeTextExplainer(class_names=classes_ordered)

# @title Setup df_test for LIME
df_test = df.loc[X_test_e.index].reset_index(drop=True)
df_test['sentiment_label'] = np.array([list(le.classes_).index(label) for label in df_test['sentiment']])
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

noise_words = {
    'israel', 'hamas', 'sep', 'user', 'the', 'a', 'an', 'and',
    'or', 'of', 'in', 'to', 'for', 'is', 'are', 'was', 'were',
    'we', 'you', 'it', 'its', 'with', 'has', 'have', 'that',
    'this', 'be', 'been', 'by', 'at', 'from', 'on', 'as', 'via',
    'will', 'just', 'see', 'over', 'all', 'will', 'wsj', 'say',
    'aren', 'our', 'why', 'they'
}

# @title LIME - Individual Examples iloc = 0(DeBERTa)

selected_texts = {
    ('hamas', 'very negative'):   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[0]['New_text'],
    ('hamas', 'mildly negative'): df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[0]['New_text'],
    ('hamas', 'neutral'):         df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[0]['New_text'],
    ('hamas', 'mildly positive'): df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[0]['New_text'],
    ('hamas', 'very positive'):   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[0]['New_text'],

    ('israel', 'very negative'):   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[0]['New_text'],
    ('israel', 'mildly negative'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==1)].iloc[0]['New_text'],
    ('israel', 'neutral'):         df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[0]['New_text'],
    ('israel', 'mildly positive'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==3)].iloc[0]['New_text'],
    ('israel', 'very positive'):   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[0]['New_text'],
}

for (entity, sentiment), text in selected_texts.items():
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=200,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"DeBERTa — {entity.upper()} — {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME__iloc0_DeBERTa_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Individual Examples iloc = 1(DeBERTa)
selected_texts = {
    ('hamas', 'very negative'):   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[1]['New_text'],
    ('hamas', 'mildly negative'): df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[1]['New_text'],
    ('hamas', 'neutral'):         df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[1]['New_text'],
    ('hamas', 'mildly positive'): df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[1]['New_text'],
    ('hamas', 'very positive'):   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[1]['New_text'],

    ('israel', 'very negative'):   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[1]['New_text'],
    ('israel', 'mildly negative'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==1)].iloc[1]['New_text'],
    ('israel', 'neutral'):         df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[1]['New_text'],
    ('israel', 'mildly positive'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==3)].iloc[1]['New_text'],
    ('israel', 'very positive'):   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[1]['New_text'],
}

for (entity, sentiment), text in selected_texts.items():
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=200,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"DeBERTa — {entity.upper()} — {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME__iloc1_DeBERTa_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Individual Examples iloc = 2(DeBERTa)
selected_texts = {
    ('hamas', 'very negative'):   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[2]['New_text'],
    ('hamas', 'mildly negative'): df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[2]['New_text'],
    ('hamas', 'neutral'):         df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[2]['New_text'],
    ('hamas', 'mildly positive'): df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[2]['New_text'],
    ('hamas', 'very positive'):   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[2]['New_text'],

    ('israel', 'very negative'):   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[2]['New_text'],
    ('israel', 'mildly negative'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==1)].iloc[2]['New_text'],
    ('israel', 'neutral'):         df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[2]['New_text'],
    ('israel', 'mildly positive'): df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==3)].iloc[2]['New_text'],
    ('israel', 'very positive'):   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[2]['New_text'],
}

for (entity, sentiment), text in selected_texts.items():
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=200,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"DeBERTa — {entity.upper()} — {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME__iloc2_DeBERTa_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Correct Predictions (DeBERTa)

def get_prediction(entity, text):
    probs = predict_proba_for_lime([text])
    return le.classes_[probs[0].argmax()]

correct = {}
for entity in ['hamas', 'israel']:
    for sentiment_label, sentiment in enumerate(le.classes_):
        match = df_test[
            (df_test["entity"] == entity) &
            (df_test["sentiment_label"] == sentiment_label)
        ]
        for i in range(len(match)):
            text = match.iloc[i]['New_text']
            if get_prediction(entity, text) == sentiment:
                correct[(entity, sentiment)] = text
                break
        else:
            print(f"[{entity} - {sentiment}] not found")

for (entity, sentiment), text in correct.items():
    exp = explainer_lime.explain_instance(
        text, predict_proba_for_lime,
        num_features=10, num_samples=200, top_labels=5
    )
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | True: {sentiment} | Predicted: {le.classes_[exp.top_labels[0]]}")
    print(f"Text: {text}")
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))
    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"DeBERTa Correct — {entity.upper()} — {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME_DeBERTa_correct_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Missclassified/nuanced predictions (DeBERTa)

misclassified = {}

target_pairs = [
    ('hamas',  'very negative',  'mildly negative'),
    ('israel', 'very negative',  'mildly negative'),
    ('hamas',  'very positive',  'mildly positive'),
    ('israel', 'very positive',  'mildly positive'),
    ('hamas',  'mildly negative', 'very negative'),
    ('israel', 'mildly negative', 'very negative'),
    ('hamas',  'mildly positive', 'very positive'),
    ('israel', 'mildly positive', 'very positive'),
]

for entity, true_sentiment, predicted_sentiment in target_pairs:
    true_label = list(le.classes_).index(true_sentiment)
    match = df_test[
        (df_test["entity"] == entity) &
        (df_test["sentiment_label"] == true_label)
    ]
    for i in range(len(match)):
        text = match.iloc[i]['New_text']
        if get_prediction(entity, text) == predicted_sentiment:
            misclassified[(entity, true_sentiment, predicted_sentiment)] = text
            print(f"[{entity} - true: {true_sentiment} → predicted: {predicted_sentiment}] found at iloc[{i}]")
            break
    else:
        print(f"[{entity} - true: {true_sentiment} → predicted: {predicted_sentiment}] not found")

for (entity, true_sentiment, predicted_sentiment), text in misclassified.items():
    exp = explainer_lime.explain_instance(
        text, predict_proba_for_lime,
        num_features=10, num_samples=200, top_labels=5
    )
    print(f"\n{'='*60}")
    print(f"Entity: {entity.capitalize()} | True: {true_sentiment} | Predicted: {predicted_sentiment}")
    print(f"Text: {text}")
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))
    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"DeBERTa Confusion — {entity.capitalize()} — {true_sentiment} → {predicted_sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME_DeBERTa_confusion_{entity}_{true_sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title Heatmap top 10 words per entity and sentiment (DeBERTa)

word_contributions = defaultdict(list)

for entity in ['hamas', 'israel']:
    for sentiment_label, sentiment in enumerate(le.classes_):
        match = df_test[
            (df_test["entity"] == entity) &
            (df_test["sentiment_label"] == sentiment_label)
        ]
        for i in range(min(5, len(match))):
            text = match.iloc[i]['New_text']
            exp = explainer_lime.explain_instance(
                text, predict_proba_for_lime,
                num_features=10, num_samples=300, top_labels=5
            )
            for word, weight in exp.as_list(label=exp.top_labels[0]):
                if word.lower() not in noise_words and len(word) > 2:
                    word_contributions[(entity, sentiment)].append((word, weight))

# Heatmap
for entity in ['hamas', 'israel']:
    top_words_per_sentiment = {}
    top_scores_per_sentiment = {}
    for sentiment in le.classes_:
        contributions = word_contributions.get((entity, sentiment), [])
        word_totals = defaultdict(float)
        for word, weight in contributions:
            word_totals[word] += weight
        top_words = sorted(word_totals.items(), key=lambda x: abs(x[1]), reverse=True)[:10]
        while len(top_words) < 10:
            top_words.append(('', 0))
        top_words_per_sentiment[sentiment]  = [w for w, _ in top_words]
        top_scores_per_sentiment[sentiment] = [s for _, s in top_words]

    score_data = pd.DataFrame(top_scores_per_sentiment, index=[f"#{i+1}" for i in range(10)])
    word_data  = pd.DataFrame(top_words_per_sentiment,  index=[f"#{i+1}" for i in range(10)])

    fig, ax = plt.subplots(figsize=(12, 6))
    sns.heatmap(score_data, ax=ax, cmap='RdYlGn', center=0,
                cbar_kws={'label': 'Contribution Score'},
                linewidths=1, linecolor='white', annot=False)

    for i in range(10):
        for j, sentiment in enumerate(le.classes_):
            word = word_data.iloc[i, j]
            ax.text(j + 0.5, i + 0.5, word, ha='center', va='center',
                    fontsize=9, fontweight='bold', color='black')

    ax.set_title(f"Top 10 Words per Sentiment — DeBERTa — {entity.capitalize()}", fontsize=13)
    ax.set_xticklabels(le.classes_, rotation=15)
    ax.set_yticklabels([f"#{i+1}" for i in range(10)], rotation=0)
    plt.tight_layout()
    plt.savefig(f"LIME_heatmap_DeBERTa_{entity}.png", dpi=300, bbox_inches='tight')
    plt.show()

"""END"""