# -*- coding: utf-8 -*-
"""thesis-bert_reproducible.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iswC3C-As08ccmfQpsxgmA6d5Z8myQwl
"""

# BERT 30 March 2026

import pandas as pd
import numpy as np
import os

from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader
from sklearn.utils.class_weight import compute_class_weight

from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_scheduler
from sklearn.preprocessing import LabelEncoder
import torch.nn.functional as F

from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm

from sklearn.metrics import classification_report, f1_score, accuracy_score

import torch

import random

df = pd.read_csv('/kaggle/input/datasets/noamladani/data-thesis-after-pre-csv/Data_Thesis_after_pre.csv')
pd.set_option('display.max_colwidth', None)
df

# @title Config
class Config:
    checkpoint = "bert-base-uncased"
    max_length = 128
    batch_size = 16
    lr = 2e-5
    epochs = 3

# @title Setting up Seeds **adjust this per run**
# SEEDS = [42, 7, 123]
# SEEDS = [42]
# SEEDS = [7]
# SEEDS = [123]

# @title Setting up device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

# @title setting entity lowercase
df['entity'] = df['entity'].replace({
    'Hamas':'hamas',
    'Israel':'israel'
    }
)

# @title Labelencoding

classes_ordered = ['very negative', 'mildly negative', 'neutral', 'mildly positive', 'very positive']

# Create encoder and manually set classes
le = LabelEncoder()
le.classes_ = np.array(classes_ordered)

df['sentiment_label'] = np.array([list(le.classes_).index(label) for label in df['sentiment']])

'''
0 = very negative
1 = mildly negative
2 = neutral
3 = mildly positive
4 = very positive
'''

df[["New_text", 'sentiment','sentiment_label']]

# @title Setting up tokenizer

tokenizer = AutoTokenizer.from_pretrained(Config.checkpoint)

def prepare_data(df, seed):
    X_train, X_temp, y_train, y_temp = train_test_split(
        df['New_text'],
        df['sentiment_label'],
        test_size=0.3,
        stratify=df['sentiment_label'],
        random_state=seed
    )


    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp,
        test_size=0.5,
        stratify=y_temp,
        random_state=seed
    )

    X_train_entity = df.loc[X_train.index, 'entity']
    X_val_entity   = df.loc[X_val.index, 'entity']
    X_test_entity  = df.loc[X_test.index, 'entity']



    return X_train, X_train_entity, y_train, \
           X_val, X_val_entity, y_val, \
           X_test, X_test_entity, y_test

def tokenize(texts, entities, tokenizer):
    combined = texts + " [SEP] " + entities

    return tokenizer(
        combined.tolist(),
        padding=True,
        truncation=True,
        max_length=Config.max_length,
        return_tensors="pt"
    )

def create_datasets(train_enc, val_enc, test_enc, y_train, y_val, y_test):
    train_dataset = TensorDataset(
        train_enc["input_ids"],
        train_enc["attention_mask"],
        torch.tensor(y_train.values)
    )

    val_dataset = TensorDataset(
        val_enc["input_ids"],
        val_enc["attention_mask"],
        torch.tensor(y_val.values)
    )

    test_dataset = TensorDataset(
        test_enc["input_ids"],
        test_enc["attention_mask"],
        torch.tensor(y_test.values)
    )

    return train_dataset, val_dataset, test_dataset

def train_model(model, train_loader, optimizer, scheduler, loss_fn, device):
    model.train()
    total_loss = 0

    for input_ids, attention_mask, labels in train_loader:
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        labels = labels.to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = loss_fn(outputs.logits, labels)

        loss.backward()
        optimizer.step()
        scheduler.step()
        optimizer.zero_grad()

        total_loss += loss.item()

    return total_loss / len(train_loader)

def evaluate(model, loader, device):
    model.eval()
    preds = []
    true = []

    with torch.no_grad():
        for input_ids, attention_mask, labels in loader:
            input_ids = input_ids.to(device)
            attention_mask = attention_mask.to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            batch_preds = torch.argmax(outputs.logits, dim=-1)

            preds.extend(batch_preds.cpu().numpy())
            true.extend(labels.numpy())

    return true, preds

def run_experiment(df, seed, tokenizer, device, le):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    # Data
    X_train, X_train_entity, y_train, \
    X_val, X_val_entity, y_val, \
    X_test, X_test_entity, y_test = prepare_data(df, seed)

    # Tokenization
    train_enc = tokenize(X_train, X_train_entity, tokenizer)
    val_enc   = tokenize(X_val, X_val_entity, tokenizer)
    test_enc  = tokenize(X_test, X_test_entity, tokenizer)

    # Dataset
    train_dataset, val_dataset, test_dataset = create_datasets(
        train_enc, val_enc, test_enc, y_train, y_val, y_test
    )

    g = torch.Generator()
    g.manual_seed(seed)
    train_loader = DataLoader(train_dataset, batch_size=Config.batch_size, shuffle=True, generator=g)
    val_loader   = DataLoader(val_dataset, batch_size=Config.batch_size)
    test_loader  = DataLoader(test_dataset, batch_size=Config.batch_size)

    model = AutoModelForSequenceClassification.from_pretrained(
    Config.checkpoint, num_labels=5).to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=Config.lr)

    loss_fn = torch.nn.CrossEntropyLoss()

    num_epochs = Config.epochs
    num_training_steps = num_epochs * len(train_loader)

    scheduler = get_scheduler(
        "linear",
        optimizer=optimizer,
        num_warmup_steps=0,
        num_training_steps=num_training_steps
    )

    # Train
    for epoch in range(num_epochs):
        loss = train_model(model, train_loader, optimizer, scheduler, loss_fn, device)
        print(f"Epoch {epoch+1} Loss: {loss:.4f}")

    # Evaluate
    y_true, y_pred = evaluate(model, test_loader, device)


    print("\n===== Classification Report =====")
    print(classification_report(y_true, y_pred, target_names=le.classes_, zero_division=0))


    macro = f1_score(y_true, y_pred, average='macro')
    weighted = f1_score(y_true, y_pred, average='weighted')
    acc = accuracy_score(y_true, y_pred)

    return macro, weighted, acc, model

results = []
for seed in SEEDS:
    print(f"\n===== Seed {seed} =====")
    macro, weighted, acc, model = run_experiment(df, seed, tokenizer, device, le)
    results.append((macro, weighted, acc))

results = np.array(results)

print("\n===== FINAL RESULTS =====")
print(f"Macro F1: {results[:,0].mean():.4f} ± {results[:,0].std():.4f}")
print(f"Weighted F1: {results[:,1].mean():.4f} ± {results[:,1].std():.4f}")
print(f"Accuracy: {results[:,2].mean():.4f} ± {results[:,2].std():.4f}")

# Seed 7
results = []
for seed in SEEDS:
    print(f"\n===== Seed {seed} =====")
    macro, weighted, acc, model = run_experiment(df, seed, tokenizer, device, le)
    results.append((macro, weighted, acc))

results = np.array(results)

print("\n===== FINAL RESULTS =====")
print(f"Macro F1: {results[:,0].mean():.4f} ± {results[:,0].std():.4f}")
print(f"Weighted F1: {results[:,1].mean():.4f} ± {results[:,1].std():.4f}")
print(f"Accuracy: {results[:,2].mean():.4f} ± {results[:,2].std():.4f}")

# Seed 123
results = []
for seed in SEEDS:
    print(f"\n===== Seed {seed} =====")
    macro, weighted, acc, model = run_experiment(df, seed, tokenizer, device, le)
    results.append((macro, weighted, acc))

results = np.array(results)

print("\n===== FINAL RESULTS =====")
print(f"Macro F1: {results[:,0].mean():.4f} ± {results[:,0].std():.4f}")
print(f"Weighted F1: {results[:,1].mean():.4f} ± {results[:,1].std():.4f}")
print(f"Accuracy: {results[:,2].mean():.4f} ± {results[:,2].std():.4f}")

# @title Entity-Level Evaluation (Seed 42)

X_train_e, X_temp_e, y_train_e, y_temp_e = train_test_split(
    df['New_text'], df['sentiment_label'],
    test_size=0.3, stratify=df['sentiment_label'], random_state=42
)
X_val_e, X_test_e, y_val_e, y_test_e = train_test_split(
    X_temp_e, y_temp_e,
    test_size=0.5, stratify=y_temp_e, random_state=42
)

df_test     = df.loc[X_test_e.index].reset_index(drop=True)
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

X_test_entity = df.loc[X_test_e.index, 'entity']
test_enc = tokenize(X_test_e, X_test_entity, tokenizer)
test_dataset = TensorDataset(
    test_enc["input_ids"],
    test_enc["attention_mask"],
    torch.tensor(y_test_e.values)
)
test_loader = DataLoader(test_dataset, batch_size=Config.batch_size)

y_true, y_pred = evaluate(model, test_loader, device)
y_pred_arr = np.array(y_pred)
y_true_arr = np.array(y_true)

hamas_preds  = y_pred_arr[hamas_mask.values]
israel_preds = y_pred_arr[israel_mask.values]
hamas_true   = y_true_arr[hamas_mask.values]
israel_true  = y_true_arr[israel_mask.values]

print("\n===== BERT - Israel Entity =====")
print(classification_report(israel_true, israel_preds, target_names=le.classes_, zero_division=0))

print("\n===== BERT - Hamas Entity =====")
print(classification_report(hamas_true, hamas_preds, target_names=le.classes_, zero_division=0))

# @title QUALITATIVE ANALYSIS (NEW)
def predict(text, model, tokenizer):
    model.eval()

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=Config.max_length
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = F.softmax(outputs.logits, dim=-1)

    score, pred = torch.max(probs, dim=1)

    return le.classes_[pred.item()], score.item()


print("\n===== QUALITATIVE ANALYSIS =====\n")

examples = list(df[['entity', 'New_text']][0:10].itertuples(index=False, name=None))

for entity, text in examples:

    input_text = entity + " [SEP] " + text
    label, score = predict(input_text, model, tokenizer)

    print(f"Entity: {entity}")
    print(f"Text: {text}")
    print(f"Prediction: {label} ({score:.3f})\n")