# -*- coding: utf-8 -*-
"""Deep_Learning_5_Sentiments_Weighted_(2)_(2) (10).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSC3_Gmd4fpLu_SZC2bCGGVOmIH2G0HW

Thesis Deep Learning Model

  - Bi-LSTM model

The Following Steps of execution

  - Import Packages
  - Load Preprocessed Dataset
  - Splitting the data 70/15/15
  - Sentiment Encoding
  - Adding balancing weight to the classes
  - Limit Vocabulary Size (20000)
  - Tokenization
  - Convert Tokens --> Sequences
  - Padding Sequences  
  - Word Embeddings (FastText) dit checken
  - Bi-LSTM Model
  - GRU model




  https://github.com/shivanisrivarshini/BiLSTM-Keras-and-Pytorch-/blob/main/bilstm_keras.py


  https://www.youtube.com/watch?v=_othJu4gBas


  https://chatgpt.com/c/69a89d9c-0a58-832d-8304-2d0bef5398ef
"""

!pip install lime
!pip install gensim

# @title Import packages
from google.colab import drive
drive.mount('/content/drive')


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string
import random
import os

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (Embedding,
                                     Bidirectional,
                                     LSTM,
                                     GRU,
                                     Conv1D,
                                     GlobalMaxPooling1D,
                                     GlobalAveragePooling1D,
                                     Dense,
                                     Dropout)


from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

from gensim.models import KeyedVectors

import shap
import lime
import lime.lime_text
from collections import defaultdict

# @title Import Dataset
df = pd.read_csv('/content/drive/MyDrive/Thesis Codes/Data/Data after preprocessing/Data_Thesis_after_pre.csv')
pd.set_option('display.max_colwidth', None)
df.head()

# @title Configuration
SEEDS = [42, 7, 123, 999, 2024, 13, 77,  31, 55, 256]
maxlen = 128
max_vocab  = 50000
embed_dim  = 300
classes_ordered = ['very negative',
                   'mildly negative',
                   'neutral',
                   'mildly positive',
                   'very positive']

# @title Lowercasing entity names
df['entity'] = df['entity'].replace({
    'Hamas'   : 'hamas',
    'Israel'  : 'israel'
})

df['Pipeline_text'] =  df['entity'] + " [SEP] " + df['New_text']

print(df['sentiment'].value_counts())

# @title Sentiment Label Encoding

le = LabelEncoder()
le.classes_ = np.array(classes_ordered)
y_encoded = np.array([list(le.classes_).index(label) for label in df['sentiment']])
'''
0 = very negative
1 = mildly negative
2 = neutral
3 = mildly positive
4 = very positive
'''
df[['sentiment']].assign(sentiment_label=y_encoded).head(5)

# @title Tokenizer (fitted on full dataset)

tokenizer = Tokenizer(num_words=max_vocab, oov_token="<OOV>")
tokenizer.fit_on_texts(df['Pipeline_text'])
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocab size: {vocab_size}")

# Sanity check
example_sentence = df['New_text'][1]
print(f"\nExample: {example_sentence}")
print(f"Sequence: {tokenizer.texts_to_sequences([example_sentence])}")

"""# Word Embeddings FastText


"""

!wget https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip
!unzip wiki-news-300d-1M.vec.zip

# @title Word Embeddings, FastText
fasttext_model = KeyedVectors.load_word2vec_format('wiki-news-300d-1M.vec')

fasttext_model.save('wiki-news-300d-1M.kv')  # binary format
# next time
fasttext_model = KeyedVectors.load('wiki-news-300d-1M.kv')  # loads in seconds

# @title Embedding Matrix
embedding_matrix = np.zeros((vocab_size, embed_dim))
missing_count = 0

for word, i in tokenizer.word_index.items():
  if i >= max_vocab:
    continue

  if word in fasttext_model:
    embedding_matrix[i] = fasttext_model[word]
  else:
    missing_count += 1

print(f"Total words in tokenizer: {len(tokenizer.word_index)}")
print(f"Words missing in FastText: {missing_count}")
print(f"Percentage missing: {missing_count / len(tokenizer.word_index) * 100:.2f}%")
print(f"Embedding matrix shape: {embedding_matrix.shape}")

"""# Modelling
Modelling consists of:


  - Setting for loop for seeds
  - Splitting data into 70/15/15
  - Padding the data
  - Class weights
  - Early Stopping
  - Creating Model Layer, with hyperparameters
  - Compiling model
  - Train Model
  - Predicting Model
  - Storing the model reuslts


  
After visualization evaluation:
  - Plot Train/Validation Accuracy/Loss
  - Amount samples in each sentiment class
  - Classification Report
  - ROC Curve
  - Confusion matrix
"""

# @title CNN Model


results_cnn = {"CNN": {"macro_f1": [], "weighted_f1": [], "acc": [], "reports": []}}
history_cnn_seed42 = None
model_cnn = None
X_test_pad_42 = None
y_test_42 = None
X_test_42 = None



for seed in SEEDS:
  print(f"\n{'='*40}\nRunning seed: {seed}\n{'='*40}")

  # Set seeds for reproducibility
  np.random.seed(seed)
  random.seed(seed)
  os.environ['PYTHONHASHSEED'] = str(seed)
  tf.random.set_seed(seed)

  # Split data
  X_train, X_temp, y_train, y_temp = train_test_split(
      df['Pipeline_text'], y_encoded,
      test_size=0.30,
      stratify=y_encoded,
      random_state=seed
    )

  X_val, X_test, y_val, y_test = train_test_split(
      X_temp, y_temp,
      test_size=0.50,
      stratify=y_temp,
      random_state=seed
    )
  print(f"Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")


  # Padding
  X_train_pad = pad_sequences(tokenizer.texts_to_sequences(X_train), maxlen=maxlen, padding='post')
  X_val_pad   = pad_sequences(tokenizer.texts_to_sequences(X_val),   maxlen=maxlen, padding='post')
  X_test_pad  = pad_sequences(tokenizer.texts_to_sequences(X_test),  maxlen=maxlen, padding='post')

  # Class weights
  classes = np.unique(y_train)
  weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
  class_weights = dict(zip(classes, weights))
  print(f"Class weights: {class_weights}")

  # Early stopping
  early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
    )




  # Creating Model Layer
  model = Sequential([
      Embedding(
      input_dim=vocab_size,       # 50000
      output_dim=embed_dim,       # 300
      weights=[embedding_matrix], # weights per words of fasttext
      input_length=maxlen,        # 100
      trainable=True
  ),
      Conv1D(filters=128, kernel_size=3, activation='relu'),
      GlobalMaxPooling1D(),
      Dense(64, activation='relu'),
      Dropout(0.5),
      Dense(5, activation='softmax')])


  model.compile(
      optimizer=Adam(learning_rate=0.001),
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy']
  )




  # Train CNN
  history = model.fit(
      X_train_pad, y_train,
      epochs=10,
      batch_size=128,
      validation_data=(X_val_pad, y_val),
      class_weight=class_weights,
      callbacks=[early_stop],
      verbose=1
  )

  # Saving history 42 for plotting later
  if seed == 42:
    history_cnn_seed42 = history
    model_cnn        = model
    X_test_pad_42    = X_test_pad
    y_test_42        = y_test
    X_test_42        = X_test




  # fitting the pipeline into first the validation set for checking overfitting
  predictions   = model.predict(X_test_pad)
  test_preds    = np.argmax(predictions, axis=1)
  macro         = f1_score(y_test, test_preds, average='macro')
  weighted      = f1_score(y_test, test_preds, average='weighted')
  acc           = accuracy_score(y_test, test_preds)

  # Test scores
  print(f"\n  CNN Seed {seed}")
  print(f"  Test Macro F1:     {macro:.4f}")
  print(f"  Test Weighted F1:  {weighted:.4f}")
  print(f"  Test Accuracy:     {acc:.4f}")


  results_cnn['CNN']["macro_f1"].append(macro)
  results_cnn['CNN']["weighted_f1"].append(weighted)
  results_cnn['CNN']["acc"].append(acc)
  results_cnn['CNN']["reports"].append(
            classification_report(y_test, test_preds, target_names=le.classes_, digits=4, output_dict=True)
        )

# @title CNN Final Results
  macro     = np.array(results_cnn["CNN"]["macro_f1"])
  weighted  = np.array(results_cnn["CNN"]["weighted_f1"])
  acc       = np.array(results_cnn["CNN"]["acc"])

  print(f"\n===== {"CNN"} Results Across Seeds =====")
  print(f"Macro F1     : {macro.mean():.4f} ± {macro.std():.4f}")
  print(f"Weighted F1  : {weighted.mean():.4f} ± {weighted.std():.4f}")
  print(f"Accuracy     : {acc.mean():.4f} ± {acc.std():.4f}")

# @title CNN Final Results
macro     = np.array(results_cnn["CNN"]["macro_f1"])
weighted  = np.array(results_cnn["CNN"]["weighted_f1"])
acc       = np.array(results_cnn["CNN"]["acc"])

print(f"\n===== {"CNN"} Results Across Seeds =====")
print(f"Macro F1     : {macro.mean():.4f} ± {macro.std():.4f}")
print(f"Weighted F1  : {weighted.mean():.4f} ± {weighted.std():.4f}")
print(f"Accuracy     : {acc.mean():.4f} ± {acc.std():.4f}")

# @title Classification Report

predictions_cnn = model_cnn.predict(X_test_pad_42)
predicted_labels_cnn = np.argmax(predictions_cnn, axis=1)

print(classification_report(
    y_test_42,
    predicted_labels_cnn,
    target_names=le.classes_,
    digits=4
))

# @title Results per Entity

df_test     = df.loc[X_test_42.index].reset_index(drop=True)
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

hamas_preds  = predicted_labels_cnn[hamas_mask.values]
israel_preds = predicted_labels_cnn[israel_mask.values]
hamas_true   = np.array(y_test_42)[hamas_mask.values]
israel_true  = np.array(y_test_42)[israel_mask.values]

print("\n===== CNN - Hamas Entity =====")
print(classification_report(hamas_true, hamas_preds, target_names=le.classes_, zero_division=0))

print("\n===== CNN - Israel Entity =====")
print(classification_report(israel_true, israel_preds, target_names=le.classes_, zero_division=0))

# @title Plot Train/Validation Accuracy/Loss


plt.plot(history_cnn_seed42.history['accuracy'], label='Train Accuracy')
plt.plot(history_cnn_seed42.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('CNN: Train vs Validation Accuracy')
plt.savefig('cnn_accuracy.png', dpi=300, bbox_inches='tight')

plt.show()

plt.plot(history_cnn_seed42.history['loss'], label='Train Loss')
plt.plot(history_cnn_seed42.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Train vs Validation Loss')
plt.savefig('cnn_loss.png', dpi=300, bbox_inches='tight')
plt.show()

# @title ROC Curve

# Binarize the labels
y_test_bin = label_binarize(y_test_42, classes=[0,1,2,3,4])

# Plot ROC for each class
plt.figure(figsize=(8,6))
for i, label in enumerate(classes_ordered):


    fpr, tpr, _ = roc_curve(y_test_bin[:, i], predictions[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{label} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--', label='Random')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Multi-class ROC Curve")
plt.legend(loc="lower right")
plt.savefig('cnn_roc_curve.png', dpi=300, bbox_inches='tight')
plt.show()

# @title  Create confusion matrix
cm = confusion_matrix(y_test_42, predicted_labels_cnn)

# Plot confusion matrix
fig, ax = plt.subplots(figsize=(7,7))

cm_display = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=classes_ordered
)

cm_display.plot(ax=ax, cmap="Blues")
plt.xticks(rotation=45)
plt.title("CNN: Confusion Matrix")
plt.tight_layout()
plt.savefig('cnn_confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

"""# GRU model

## Modelling
Modelling consists of:


  - Setting for loop for seeds
  - Splitting data into 70/15/15
  - Padding the data
  - Class weights
  - Early Stopping
  - Creating Model Layer, with hyperparameters
  - Compiling model
  - Train Model
  - Predicting Model
  - Storing the model reuslts


  
## After visualization evaluation:
  - Plot Train/Validation Accuracy/Loss
  - Amount samples in each sentiment class
  - Classification Report
  - ROC Curve
  - Confusion matrix
"""

# @title GRU Training Loop

results_GRU = {"GRU": {"macro_f1": [], "weighted_f1": [], "acc": [], "reports": []}}
history_seed_42_gru = None
model_gru = None
X_test_pad_42 = None
y_test_42 = None
X_test_42 = None




for seed in SEEDS:
  print(f"\n{'='*40}\nRunning seed: {seed}\n{'='*40}")

  # Set seeds for reproducibility
  np.random.seed(seed)
  random.seed(seed)
  os.environ['PYTHONHASHSEED'] = str(seed)
  tf.random.set_seed(seed)

  # Split data
  X_train, X_temp, y_train, y_temp = train_test_split(
      df['Pipeline_text'], y_encoded,
      test_size=0.30,
      stratify=y_encoded,
      random_state=seed
    )

  X_val, X_test, y_val, y_test = train_test_split(
      X_temp, y_temp,
      test_size=0.50,
      stratify=y_temp,
      random_state=seed
    )
  print(f"Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")


  # Pad sequences
  X_train_pad = pad_sequences(tokenizer.texts_to_sequences(X_train), maxlen=maxlen, padding='post')
  X_val_pad   = pad_sequences(tokenizer.texts_to_sequences(X_val),   maxlen=maxlen, padding='post')
  X_test_pad  = pad_sequences(tokenizer.texts_to_sequences(X_test),  maxlen=maxlen, padding='post')


  # Class weights
  classes = np.unique(y_train)
  weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
  class_weights = dict(zip(classes, weights))
  print(f"Class weights: {class_weights}")


  # Early stopping
  early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
    )




  # Creating Model Layer
  model = Sequential([
      Embedding(
      input_dim=vocab_size,       # 50000
      output_dim=embed_dim,        # 300
      weights=[embedding_matrix], # weights per words of fasttext
      input_length=maxlen,        # 100
      trainable=True
  ),

  GRU(128, return_sequences=True),
  Dropout(0.3),
  GlobalAveragePooling1D(),
  Dense(64, activation='relu'),
  Dropout(0.3),
  Dense(5, activation='softmax')
  ])


  model.compile(
      optimizer=Adam(learning_rate=0.001),
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy']
      )



  # Train GRU
  history = model.fit(
      X_train_pad, y_train,
      epochs=10,
      batch_size=128,
      validation_data=(X_val_pad, y_val),
      class_weight=class_weights,
      callbacks=[early_stop],
      verbose=1
  )

  # Saving history 42 for plotting later
  if seed == 42:
    history_seed_42_gru = history
    model_gru           = model
    X_test_pad_42       = X_test_pad
    y_test_42           = y_test
    X_test_42           = X_test




  # fitting the pipeline into first the validation set for checking overfitting
  predictions   = model.predict(X_test_pad)
  preds         = np.argmax(predictions, axis=1)
  macro         = f1_score(y_test, preds, average='macro')
  weighted      = f1_score(y_test, preds, average='weighted')
  acc           = accuracy_score(y_test, preds)

  # Test scores
  print(f"\n  GRU Seed {seed}")
  print(f"  Test Macro F1:     {macro:.4f}")
  print(f"  Test Weighted F1:  {weighted:.4f}")
  print(f"  Test Accuracy:     {acc:.4f}")


  results_GRU['GRU']["macro_f1"].append(macro)
  results_GRU['GRU']["weighted_f1"].append(weighted)
  results_GRU['GRU']["acc"].append(acc)
  results_GRU['GRU']["reports"].append(
            classification_report(y_test, preds, target_names=le.classes_, digits=4, output_dict = True)
        )

  print(f"\nMean Macro F1: {np.mean(results_GRU['GRU']['macro_f1']):.4f}")
  print(f"Mean Weighted F1: {np.mean(results_GRU['GRU']['weighted_f1']):.4f}")

# @title Final Results
macro = np.array(results_GRU["GRU"]["macro_f1"])
weighted = np.array(results_GRU["GRU"]["weighted_f1"])
acc = np.array(results_GRU["GRU"]["acc"])

print(f"\n===== {"GRU"} Results Across Seeds =====")
print(f"Macro F1     : {macro.mean():.4f} ± {macro.std():.4f}")
print(f"Weighted F1  : {weighted.mean():.4f} ± {weighted.std():.4f}")
print(f"Accuracy     : {acc.mean():.4f} ± {acc.std():.4f}")

# @title Classification Report

predictions_gru = model_gru.predict(X_test_pad_42)
predicted_labels_gru = np.argmax(predictions_gru, axis=1)

print(classification_report(
    y_test_42,
    predicted_labels_gru,
    target_names=le.classes_,
    digits=4
))

# @title Results per Entity

df_test     = df.loc[X_test_42.index].reset_index(drop=True)
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

hamas_preds  = predicted_labels_gru[hamas_mask.values]
israel_preds = predicted_labels_gru[israel_mask.values]
hamas_true   = np.array(y_test_42)[hamas_mask.values]
israel_true  = np.array(y_test_42)[israel_mask.values]

print("\n===== GRU - Hamas Entity =====")
print(classification_report(hamas_true, hamas_preds, target_names=le.classes_, zero_division=0))

print("\n===== GRU - Israel Entity =====")
print(classification_report(israel_true, israel_preds, target_names=le.classes_, zero_division=0))

# @title Plot Train/Validation Accuracy/Loss


plt.plot(history_seed_42_gru.history['accuracy'], label='Train Accuracy')
plt.plot(history_seed_42_gru.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('GRU: Train vs Validation Accuracy')
plt.savefig('gru_accuracy.png', dpi=300, bbox_inches='tight')
plt.show()

plt.plot(history_seed_42_gru.history['loss'], label='Train Loss')
plt.plot(history_seed_42_gru.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('GRU: Train vs Validation Loss')
plt.savefig('gru_loss.png', dpi=300, bbox_inches='tight')
plt.show()

# @title  Create confusion matrix
cm = confusion_matrix(y_test_42, predicted_labels_gru)

# Plot confusion matrix
fig, ax = plt.subplots(figsize=(7,7))

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=classes_ordered
).plot(ax=ax, cmap="Blues")
plt.xticks(rotation=45)
plt.title("GRU: Confusion Matrix")
plt.tight_layout()
plt.savefig('gru_confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# @title ROC Curve


# Binarize the labels
y_test_bin = label_binarize(y_test_42, classes=[0,1,2,3,4])

# Plot ROC for each class
plt.figure(figsize=(8,6))
for i, label in enumerate(classes_ordered):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], predictions_gru[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{label} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--', label='Random')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("GRU: Multi-class ROC Curve")
plt.legend(loc="lower right")
plt.savefig('gru_roc_curve.png', dpi=300, bbox_inches='tight')
plt.show()

"""# Bi-LSTM model

## Modelling
Modelling consists of:


  - Setting for loop for seeds
  - Splitting data into 70/15/15
  - Padding the data
  - Class weights
  - Early Stopping
  - Creating Model Layer, with hyperparameters
  - Compiling model
  - Train Model
  - Predicting Model
  - Storing the model reuslts


  
## After visualization evaluation:
  - Plot Train/Validation Accuracy/Loss
  - Amount samples in each sentiment class
  - Classification Report
  - ROC Curve
  - Confusion matrix
"""

# @title Bi-LSTM



results_Bi_LSTM = {"Bi-LSTM": {"macro_f1": [], "weighted_f1": [], "acc": [], "reports": []}}
history_seed_42_bi_lstm = None
model_bilstm = None
X_test_pad_42 = None
y_test_42 = None
X_test_42 = None


for seed in SEEDS:
  print(f"\n{'='*40}\nRunning seed: {seed}\n{'='*40}")

  # Set seeds for reproducibility
  np.random.seed(seed)
  random.seed(seed)
  os.environ['PYTHONHASHSEED'] = str(seed)
  tf.random.set_seed(seed)

  # Split data
  X_train, X_temp, y_train, y_temp = train_test_split(
      df['Pipeline_text'], y_encoded,
      test_size=0.30,
      stratify=y_encoded,
      random_state=seed
    )

  X_val, X_test, y_val, y_test = train_test_split(
      X_temp, y_temp,
      test_size=0.50,
      stratify=y_temp,
      random_state=seed
    )
  print(f"Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")

  # Pad sequences
  X_train_pad = pad_sequences(tokenizer.texts_to_sequences(X_train), maxlen=maxlen, padding='post')
  X_val_pad   = pad_sequences(tokenizer.texts_to_sequences(X_val),   maxlen=maxlen, padding='post')
  X_test_pad  = pad_sequences(tokenizer.texts_to_sequences(X_test),  maxlen=maxlen, padding='post')

    # Class weights
  classes = np.unique(y_train)
  weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)
  class_weights = dict(zip(classes, weights))
  print(f"Class weights: {class_weights}")

  # Early stopping
  early_stop = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
    )




  # Creating Model Layer
  model = Sequential([
      Embedding(
      input_dim=vocab_size,       # 50000
      output_dim=embed_dim,       # dimensions
      weights=[embedding_matrix], # weights per words of fasttext
      input_length=maxlen,        # length tweet words
      trainable=True
  ),


  Bidirectional(LSTM(128, return_sequences=True)),
  Dropout(0.3),
  GlobalAveragePooling1D(),
  Dense(64, activation='relu'),
  Dropout(0.3),
  Dense(5, activation='softmax')])


  model.compile(
      optimizer=Adam(learning_rate=0.001),
      loss='sparse_categorical_crossentropy',
      metrics=['accuracy']
      )





  # Train Bi-LSTM
  history = model.fit(
      X_train_pad, y_train,
      epochs=10,
      batch_size= 128,
      validation_data=(X_val_pad, y_val),
      class_weight=class_weights,
      callbacks=[early_stop],
      verbose=1
  )

  # Saving history 42 for plotting later
  if seed == 42:
    history_seed_42_bi_lstm = history
    model_bilstm    = model
    X_test_pad_42   = X_test_pad
    y_test_42       = y_test
    X_test_42       = X_test





  # fitting the pipeline into first the validation set for checking overfitting
  predictions   = model.predict(X_test_pad)


  # predicting on Test set
  test_preds    = np.argmax(predictions, axis=1)
  macro         = f1_score(y_test, test_preds, average='macro')
  weighted      = f1_score(y_test, test_preds, average='weighted')
  acc           = accuracy_score(y_test, test_preds)

  # Test scores
  print(f"\n  Bi-LSTM Seed {seed}")
  print(f"  Test Macro F1:     {macro:.4f}")
  print(f"  Test Weighted F1:  {weighted:.4f}")
  print(f"  Test Accuracy:     {acc:.4f}")


  results_Bi_LSTM['Bi-LSTM']["macro_f1"].append(macro)
  results_Bi_LSTM['Bi-LSTM']["weighted_f1"].append(weighted)
  results_Bi_LSTM['Bi-LSTM']["acc"].append(acc)
  results_Bi_LSTM['Bi-LSTM']["reports"].append(
            classification_report(y_test, test_preds, target_names=le.classes_, digits=4, output_dict = True)
        )
  print(f"\nMean Macro F1: {np.mean(results_Bi_LSTM['Bi-LSTM']['macro_f1']):.4f}")
  print(f"Mean Weighted F1: {np.mean(results_Bi_LSTM['Bi-LSTM']['weighted_f1']):.4f}")

macro = np.array(results_Bi_LSTM["Bi-LSTM"]["macro_f1"])
weighted = np.array(results_Bi_LSTM["Bi-LSTM"]["weighted_f1"])
acc = np.array(results_Bi_LSTM["Bi-LSTM"]["acc"])

print(f"\n===== {"Bi-LSTM"} Results Across Seeds =====")
print(f"Macro F1     : {macro.mean():.4f} ± {macro.std():.4f}")
print(f"Weighted F1  : {weighted.mean():.4f} ± {weighted.std():.4f}")
print(f"Accuracy     : {acc.mean():.4f} ± {acc.std():.4f}")

# @title Classification Report

predictions_bilstm = model_bilstm.predict(X_test_pad_42)
predicted_labels_bilstm = np.argmax(predictions_bilstm, axis=1)

print(classification_report(
    y_test_42,
    predicted_labels_bilstm,
    target_names=le.classes_,
    digits=4
))

# @title Results per Entity

df_test     = df.loc[X_test_42.index].reset_index(drop=True)
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

hamas_preds  = predicted_labels_bilstm[hamas_mask.values]
israel_preds = predicted_labels_bilstm[israel_mask.values]
hamas_true   = np.array(y_test_42)[hamas_mask.values]
israel_true  = np.array(y_test_42)[israel_mask.values]

print("\n===== BiLSTM - Hamas Entity =====")
print(classification_report(hamas_true, hamas_preds, target_names=le.classes_, zero_division=0))

print("\n===== BiLSTM - Israel Entity =====")
print(classification_report(israel_true, israel_preds, target_names=le.classes_, zero_division=0))

# @title Plot Train/Validation Accuracy/Loss


plt.plot(history_seed_42_bi_lstm.history['accuracy'], label='Train Accuracy')
plt.plot(history_seed_42_bi_lstm.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('BiLSTM: Train vs Validation Accuracy')
plt.savefig('bilstm_accuracy.png', dpi=300, bbox_inches='tight')
plt.show()

plt.plot(history_seed_42_bi_lstm.history['loss'], label='Train Loss')
plt.plot(history_seed_42_bi_lstm.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Train vs Validation Loss')
plt.savefig('bilstm_loss.png', dpi=300, bbox_inches='tight')
plt.show()

# @title  Create confusion matrix
cm = confusion_matrix(y_test_42, predicted_labels_bilstm)

# Plot confusion matrix
fig, ax = plt.subplots(figsize=(7,7))

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=classes_ordered
).plot(ax=ax, cmap="Blues")
plt.xticks(rotation=45)
plt.title("Bi-LSTM: Confusion Matrix")
plt.tight_layout()
plt.savefig('BiLSTM_confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# @title  Create confusion matrix
cm = confusion_matrix(y_test_42, predicted_labels_bilstm)

# Plot confusion matrix
fig, ax = plt.subplots(figsize=(7,7))

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=classes_ordered
).plot(ax=ax, cmap="Blues")
plt.xticks(rotation=45)
plt.title("Bi-LSTM: Confusion Matrix")
plt.tight_layout()
plt.savefig('BiLSTM_confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

# @title ROC Curve

# Binarize the labels
y_test_bin = label_binarize(y_test_42, classes=[0,1,2,3,4])


# Plot ROC for each class
plt.figure(figsize=(8,6))
for i, label in enumerate(classes_ordered):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], predictions_bilstm[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{label} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--', label='Random')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Multi-class ROC Curve")
plt.legend(loc="lower right")
plt.savefig('bilstm_roc_curve.png', dpi=300, bbox_inches='tight')
plt.show()

"""LIME

# XAI Setup

Getting the best model with the best seed

  - 3 examples of per entity and sentiments
  - Top contributing words SNS plot
"""

# @title Setup df_test for LIME
def predict_proba_for_lime(texts):
    seqs   = tokenizer.texts_to_sequences(texts)
    padded = pad_sequences(seqs, maxlen=maxlen, padding='post')
    return model_bilstm.predict(padded, verbose=0)

explainer_lime = lime.lime_text.LimeTextExplainer(class_names=classes_ordered)

df_test = df.loc[X_test_42.index].reset_index(drop=True)
df_test['sentiment_label'] = np.array([list(le.classes_).index(label) for label in df_test['sentiment']])
hamas_mask  = df_test["entity"] == "hamas"
israel_mask = df_test["entity"] == "israel"

noise_words = {
    'israel', 'hamas', 'sep', 'user', 'the', 'a', 'an', 'and',
    'or', 'of', 'in', 'to', 'for', 'is', 'are', 'was', 'were',
    'we', 'you', 'it', 'its', 'with', 'has', 'have', 'that',
    'this', 'be', 'been', 'by', 'at', 'from', 'on', 'as', 'via',
    'see', 'did', 'SEP' , '873', 'our', 'but'

}

# @title LIME - Individual Examples (BiLSTM)

'''
0 = very negative
1 = mildly negative
2 = neutral
3 = mildly positive
4 = very positive
'''

selected_texts = [
    ('hamas', 'very negative',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[1]['Pipeline_text']),
    ('hamas', 'very negative',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[5]['Pipeline_text']),
    ('hamas', 'very negative',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[10]['Pipeline_text']),
    ('hamas', 'very negative',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==0)].iloc[15]['Pipeline_text']),
    ('hamas', 'mildly negative', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[1]['Pipeline_text']),
    ('hamas', 'mildly negative', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[5]['Pipeline_text']),
    ('hamas', 'mildly negative', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[10]['Pipeline_text']),
    ('hamas', 'mildly negative', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==1)].iloc[15]['Pipeline_text']),
    ('hamas', 'neutral',         df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[1]['Pipeline_text']),
    ('hamas', 'neutral',         df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[5]['Pipeline_text']),
    ('hamas', 'neutral',         df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[10]['Pipeline_text']),
    ('hamas', 'neutral',         df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==2)].iloc[15]['Pipeline_text']),
    ('hamas', 'mildly positive', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[1]['Pipeline_text']),
    ('hamas', 'mildly positive', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[5]['Pipeline_text']),
    ('hamas', 'mildly positive', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[10]['Pipeline_text']),
    ('hamas', 'mildly positive', df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==3)].iloc[15]['Pipeline_text']),
    ('hamas', 'very positive',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[1]['Pipeline_text']),
    ('hamas', 'very positive',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[5]['Pipeline_text']),
    ('hamas', 'very positive',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[10]['Pipeline_text']),
    ('hamas', 'very positive',   df_test[(df_test['entity']=='hamas')  & (df_test['sentiment_label']==4)].iloc[15]['Pipeline_text']),

    ('israel', 'very negative',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[1]['Pipeline_text']),
    ('israel', 'very negative',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[10]['Pipeline_text']),
    ('israel', 'very negative',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[15]['Pipeline_text']),
    ('israel', 'very negative',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==0)].iloc[20]['Pipeline_text']),
    ('israel', 'mildly negative', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==1)].iloc[1]['Pipeline_text']),
    ('israel', 'mildly negative', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==1)].iloc[10]['Pipeline_text']),
    ('israel', 'mildly negative', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==1)].iloc[15]['Pipeline_text']),
    ('israel', 'mildly negative', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==1)].iloc[20]['Pipeline_text']),
    ('israel', 'neutral',         df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[1]['Pipeline_text']),
    ('israel', 'neutral',         df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[10]['Pipeline_text']),
    ('israel', 'neutral',         df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[15]['Pipeline_text']),
    ('israel', 'neutral',         df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==2)].iloc[20]['Pipeline_text']),
    ('israel', 'mildly positive', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==3)].iloc[1]['Pipeline_text']),
    ('israel', 'mildly positive', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==3)].iloc[10]['Pipeline_text']),
    ('israel', 'mildly positive', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==3)].iloc[15]['Pipeline_text']),
    ('israel', 'mildly positive', df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==3)].iloc[20]['Pipeline_text']),
    ('israel', 'very positive',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[1]['Pipeline_text']),
    ('israel', 'very positive',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[10]['Pipeline_text']),
    ('israel', 'very positive',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[15]['Pipeline_text']),
    ('israel', 'very positive',   df_test[(df_test['entity']=='israel') & (df_test['sentiment_label']==4)].iloc[20]['Pipeline_text']),
]

for entity, sentiment, text in selected_texts:  # ← unpack 3 values now
    text = text.replace("hamas [SEP] ", "").replace("israel [SEP] ", "")
    print(f"\n{'='*60}")
    print(f"Entity: {entity.upper()} | Sentiment: {sentiment}")
    print(f"Text: {text}")
    print(f"Predicted: {le.classes_[predict_proba_for_lime([text])[0].argmax()]}")

    exp = explainer_lime.explain_instance(
        text,
        predict_proba_for_lime,
        num_features=10,
        num_samples=1000,
        top_labels=5
    )
    exp.show_in_notebook(text=True, labels=(exp.top_labels[0],))

    fig = exp.as_pyplot_figure(label=exp.top_labels[0])
    plt.title(f"BiLSTM — {entity.upper()} — {sentiment}")
    plt.tight_layout()
    plt.savefig(f"LIME_BiLSTM_{entity}_{sentiment}.png", dpi=300, bbox_inches='tight')
    plt.close()

# @title LIME - Collect Word Contributions + Heatmap (BiLSTM)

word_contributions = defaultdict(list)

for entity in ['hamas', 'israel']:
    for sentiment_label, sentiment in enumerate(le.classes_):
        match = df_test[
            (df_test["entity"] == entity) &
            (df_test["sentiment_label"] == sentiment_label)
        ]
        for i in range(min(20, len(match))):
            text = match.iloc[i]['Pipeline_text']
            text = text.replace("hamas [SEP] ", "").replace("israel [SEP] ", "")
            exp = explainer_lime.explain_instance(
                text, predict_proba_for_lime,
                num_features=10, num_samples=1000, top_labels=5
            )
            for word, weight in exp.as_list(label=exp.top_labels[0]):
                if word.lower() not in noise_words and len(word) > 2:
                    word_contributions[(entity, sentiment)].append((word, weight))




#  Heatmap
for entity in ['hamas', 'israel']:

    top_words_per_sentiment = {}
    top_scores_per_sentiment = {}
    for sentiment in le.classes_:
        contributions = word_contributions.get((entity, sentiment), [])
        word_totals = defaultdict(float)
        for word, weight in contributions:
            word_totals[word] += weight
        top_words = sorted(word_totals.items(), key=lambda x: abs(x[1]), reverse=True)[:10]
        while len(top_words) < 10:
            top_words.append(('', 0))
        top_words_per_sentiment[sentiment]  = [w for w, _ in top_words]
        top_scores_per_sentiment[sentiment] = [s for _, s in top_words]

    score_data = pd.DataFrame(top_scores_per_sentiment,
                               index=[f"#{i+1}" for i in range(10)])
    word_data  = pd.DataFrame(top_words_per_sentiment,
                               index=[f"#{i+1}" for i in range(10)])

    fig, ax = plt.subplots(figsize=(12, 4))
    sns.heatmap(score_data, ax=ax, cmap='RdYlGn', center=0,
                cbar_kws={'label': 'Contribution Score'},
                linewidths=1, linecolor='white', annot=False)

    for i in range(10):
        for j, sentiment in enumerate(le.classes_):
            word = word_data.iloc[i, j] if j < word_data.shape[1] else ''
            ax.text(j + 0.5, i + 0.5, word, ha='center', va='center',
                    fontsize=11, fontweight='bold', color='black')

    ax.set_title(f"Top 10 Words per Sentiment — BiLSTM — {entity.upper()}", fontsize=13)
    ax.set_xticklabels(le.classes_, rotation=15)
    ax.set_yticklabels([f"#{i+1}" for i in range(10)], rotation=0)
    plt.tight_layout()
    plt.savefig(f"LIME_heatmap_BiLSTM_{entity}.png", dpi=300, bbox_inches='tight')
    plt.show()

"""# End"""